# Generated by Django 4.2.11 on 2024-04-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city'),
        ),
    ]
