# Generated by Django 4.2.11 on 2024-08-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='city',
            new_name='bank_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='user_city',
        ),
    ]
